version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - openai.api.key=${OPENAI_API_KEY}
    restart: unless-stopped
