services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AMADEUS_API_CLIENTID=${AMADEUS_API_CLIENTID}
      - AMADEUS_API_CLIENTSECRET=${AMADEUS_API_CLIENTSECRET}
      - AMADEUS_API_BASEURL=${AMADEUS_API_BASEURL:-https://test.api.amadeus.com}
    restart: unless-stopped
