version: '3.8'

services:
  globetrotter-services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AMADEUS_API_CLIENTID=${AMADEUS_API_CLIENTID}
      - AMADEUS_API_CLIENTSECRET=${AMADEUS_API_CLIENTSECRET}
      - AMADEUS_API_BASEURL=https://test.api.amadeus.com
      - LOGGING_LEVEL_COM_GLOBETROTTER=DEBUG
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_PATTERN_CONSOLE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    restart: unless-stopped

  globetrotter-bff:
    build:
      context: ../globetrotter-bff
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AMADEUS_API_CLIENTID=${AMADEUS_API_CLIENTID}
      - AMADEUS_API_CLIENTSECRET=${AMADEUS_API_CLIENTSECRET}
      - AMADEUS_API_BASEURL=https://test.api.amadeus.com
    restart: unless-stopped
    depends_on:
      - globetrotter-services 