version: '3.8'

services:
  globetrotter-services:
    build:
      context: .
      dockerfile: Dockerfile
    image: globetrotter-services:0.0.1-SNAPSHOT
    container_name: globetrotter-services
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - AMADEUS_API_CLIENTID=${AMADEUS_API_CLIENTID}
      - AMADEUS_API_CLIENTSECRET=${AMADEUS_API_CLIENTSECRET}
      - AMADEUS_API_BASEURL=https://test.api.amadeus.com
      - LOGGING_LEVEL_COM_GLOBETROTTER=DEBUG
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_PATTERN_CONSOLE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    restart: unless-stopped
    networks:
      - globetrotter-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  globetrotter-network:
    external: true
