server:
  port: 8080
spring:
  application:
    name: globetrotter-services
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: health,info
amadeus:
  api:
    clientId: ${AMADEUS_API_CLIENTID}
    clientSecret: ${AMADEUS_API_CLIENTSECRET}
    baseUrl: ${AMADEUS_API_BASEURL:https://test.api.amadeus.com}
openai:
  api:
    key: ${OPENAI_API_KEY}
    model: ${OPENAI_API_MODEL:gpt-3.5-turbo-instruct}
