server:
  port: 8080
spring:
  application:
    name: globetrotter-services
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: health,info
amadeus.api.clientId=${AMADEUS_API_CLIENTID}
amadeus.api.clientSecret=${AMADEUS_API_CLIENTSECRET}
amadeus.api.baseUrl=${AMADEUS_API_BASEURL:https://test.api.amadeus.com}
